### ISSUE TITLE
Enable code generation in the generate-test-sources phase

### ISSUE THREAD

**Issue by jrosczak** [eclipse/xtext-maven#111]
The default phase for this plugin is "generate-sources" and the resolution scope is "compile". Therefore it is not possible / easy to use this plugin with a language that generates test classes, which for instance use the junit test framework.

The problem is that the junit classes are usually not available on the compile classpath in a normal maven project, but on the test classpath.

I would like to propose to create a new mojo for the "generate-test-sources" phase, similar to what the xtend-maven plugin already has.

**Comment by cdietrich** [comment]
@kthoms @szarnekow what do you think?

**Comment by szarnekow** [comment]
Extracting the common parts into a base class to avoid XtextTestGenerator being an instance of XtextGenerator sounds favourable to me, too.

**Comment by cdietrich** [comment]
Fixed in 2.21.

**Comment by cdietrich** [comment]
@jrosczak could you please write a few lines for 
https://github.com/eclipse/xtext/blob/website-master/xtext-website/_posts/releasenotes/2020-03-03-version-2-21-0.md

**Comment by cdietrich** [comment]
Fixed in 2.21
