### ISSUE TITLE
mvn install gets stuck

### ISSUE THREAD

**Issue by OrenGitHub** [eclipse/xtext-maven#131]
Here is what I did
```
$ git clone https://github.com/eclipse/xtext-maven.git
$ cd xtext-maven/org.eclipse.xtext.maven.parent
$ mvn install
```
It seems to hand indefinitely, last stdout message:
```
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default) @ xtext-maven-plugin ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.eclipse.xtext.maven.plugin.XtextGeneratorIT
^Z
[4]+  Stopped                 mvn install
```

**Comment by cdietrich** [comment]
can you please provide jstack?

**Comment by OrenGitHub** [comment]
I only waited for a minute or so, maybe it just didn't finish?
Sorry I'm clueless, I don't even know what a jstack is

**Comment by cdietrich** [comment]
there is a jstack command in java which shows you what threads are currently doing. and if something changes if you execute it multiple times with a few secs delay

**Comment by cdietrich** [comment]
```
[INFO] Reactor Summary for Xtext Maven Plugin Parent POM 2.23.0-SNAPSHOT:
[INFO]
[INFO] Xtext Maven Plugin Parent POM ...................... SUCCESS [  2.940 s]
[INFO] Xtext Maven Plugin ................................. SUCCESS [18:36 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18:39 min
[INFO] Finished at: 2020-07-30T13:54:22+02:00
```

**Comment by OrenGitHub** [comment]
After more than one hour still no change.
Here is the output of running `jps`. Which PID should I use for jstack?
```
7584 Launcher
11266 surefirebooter13416462354599958060.jar
20739 Jps
6147 Launcher
11172 Launcher
3237 Launcher
7685 surefirebooter9285513727221816376.jar
4805 surefirebooter16338682831466923567.jar
16230 Launcher
6438 Launcher
30150 org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar
9703 surefirebooter18112000788112576894.jar
4681 Launcher
5196 XMLServerLauncher
4397 Launcher
3309 surefirebooter12587618748103809748.jar
9614 Launcher
5201 XMLServerLauncher
8021 Launcher
5176 Launcher
10041 Launcher
6238 surefirebooter8422477550861656694.jar
```

**Comment by cdietrich** [comment]
i propose that you simply run the command and wait 20-30 mins.

**Comment by OrenGitHub** [comment]
OK will do.
When I type
```
$ mvn compile
```
Then everything ends in a sec:
```
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ xtext-maven-plugin ---
[INFO] Nothing to compile - all classes are up to date
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.104 s
[INFO] Finished at: 2020-07-30T16:44:21+03:00
[INFO] ------------------------------------------------------------------------
```
Is the `T E S T S` part mandatory?

**Comment by cdietrich** [comment]
on jenkins it is. but of course you dont have to use them if you dont want (am not sure what your goal is)

**Comment by OrenGitHub** [comment]
- I want to a `hello-xtext-world` application, compile-able from command line, (ideally with `mvn compile`)
 - It will accept a `my_grammar.xtext` and produces `my_interpreter.jar`
 - `java -jar my_interpreter.jar input.my_dsl` will determine if it has correct syntax,
 - and if it does, will interpret its meaning according to my specification

I hope I'm in the right place for that (?)

**Comment by cdietrich** [comment]
nope. this is for the xtext-maven-plugin which is used to translate e.g. yourdsl files to generated code (e.g. java, txt, ...)
to create a Xtext project there is 

https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/cli/CliProjectsCreatorMain.java

which basically allow you to do what the new xtext project wizard does from a java main

then you would need to call maven or gradle on the result (maybe modify the code to create the java main that does call your interpreter and produce a uber jar/app)

(am not sure if in understood your usecase correct)

**Comment by OrenGitHub** [comment]
@cdietrich  Thanks for your patience!
What still bothers me is that in order to compile `CliProjectsCreatorMain.java`
I need some maven `pom.xml` (no ?) Otherwise a ton of jars will be missing (?)
Also, from what you wrote, I understand that input dsl files (with correct syntax I guess)
are transformed into actual java files? which can be linked and run afterwards?

**Comment by cdietrich** [comment]
Hi I cannot follow you https://search.maven.org/artifact/org.eclipse.xtext/org.eclipse.xtext.xtext.wizard/2.22.0/jar

**Comment by OrenGitHub** [comment]
OK, I'll try to post in SO in case I can't solve it --
Thanks again for your help!
