### ISSUE TITLE
Trace options in generator are ignored

### ISSUE THREAD

**Issue by imhotep82** [eclipse/xtext-maven#139]
When I use the generator to also attach trace information, trace options (using DSL as source etc.) are ignored.

Options in POM.xml :
```xml
<language>
	<setup>com.StandaloneSetupGenerated</setup>
	<javaSupport>false</javaSupport>
	<outputConfigurations>
		<outputConfiguration>
			<installDslAsPrimarySource>true</installDslAsPrimarySource>
			<hideSyntheticLocalVariables>true</hideSyntheticLocalVariables>
			(...)
		</outputConfiguration>
	</outputConfigurations>
</language>
```

Workaround: 
Attach them later with Xtend (disabling compilation) (also POM.xml) :

```xml
<plugin>
<groupId>org.eclipse.xtend</groupId>
<artifactId>xtend-maven-plugin</artifactId>
<version>2.22.0</version>
<executions>
	<execution>
		<goals>
			<goal>xtend-install-debug-info</goal>
			<goal>xtend-test-install-debug-info</goal>
		</goals>
		<configuration>
			<hideSyntheticVariables>true</hideSyntheticVariables>
			<xtendAsPrimaryDebugSource>true</xtendAsPrimaryDebugSource>
			<outputDirectory>src-gen</outputDirectory>
			<testOutputDirectory>src-gen</testOutputDirectory>
		</configuration>
	</execution>
</executions>
</plugin>
```

FYI: We use this for surefire + jacoco to show code coverage on an Xbase grammar in Sonarqube.

It would be nice if this behaviour could either be:
* Documented in the README + options removed + hint to use Xtend
* Re-used from Xtend by using this module as a dependency and invoking the appropriate methods

**Comment by cdietrich** [comment]
hi. would be nice if you could debug what happens here.

**Comment by imhotep82** [comment]
I didn't find any occurrences of `org.eclipse.xtext.generator.OutputConfiguration.isInstallDslAsPrimarySource()` in xtext-core.
There is one mention in `https://github.com/eclipse/xtext-eclipse/blob/61cfaa76f415daae3fe36c0fafcf1123bcfe83e6/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/smap/DebugSourceInstallingCompilationParticipant.java`, though.

**Comment by cdietrich** [comment]
see also https://github.com/xtext/xtext-gradle-plugin/blob/996a26bb281bf3828c143067f138a582fe5eb149/xtext-gradle-builder/src/main/java/org/xtext/gradle/builder/DebugInfoInstaller.xtend

**Comment by imhotep82** [comment]
I guess this bug concerns the StandaloneBuilder then? I could check and create a PR there to fix this issue...

**Comment by cdietrich** [comment]
I don’t know if this is easily possible as you would have to hook into the classes built by maven java compiler

**Comment by imhotep82** [comment]
On second thought, this is more a lifecycle issue. the xtext-maven MOJOs generate the java (test) source files, then the maven compiler kicks in and at last, there should be additional lifecycle steps bound to the MOJOs (process-classes or process-test-classes). Would it be OK to add an additional lifecycle phase to the MOJOs?

**Comment by cdietrich** [comment]
i assume we need separate mojos for it as we have it for the xtend-maven-plugin

**Comment by imhotep82** [comment]
See my PR. I have two. One for target/classes and one for target/test-classes

**Comment by imhotep82** [comment]
#141

**Comment by cdietrich** [comment]
fixed  in 2.26

**Comment by cdietrich** [comment]
@imhotep82 maybe you can add a few words here https://github.com/eclipse/xtext/blob/website-master/xtext-website/documentation/350_continuous_integration.md

**Comment by imhotep82** [comment]
Will do, I'll create a PR from my fork to master, is this correct?

**Comment by cdietrich** [comment]
no website-master

**Comment by imhotep82** [comment]
Done. https://github.com/eclipse/xtext/pull/1965

**Comment by cdietrich** [comment]
i dont know. i assume no

**Comment by OLibutzki** [comment]
Seems not to solve it...
