### ISSUE TITLE
Move to Maven/Tycho for projects and build infrastructure

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext-maven#198]
See also https://github.com/eclipse/xtext-web/issues/400 eclipse/xtext-eclipse#1992 eclipse/xtext-lib#499 and eclipse/xtext-core#2052 eclipse/xtext-extras#858 eclipse/xtext-xtend#1445

The project is already Maven-based but I'd like to harmonize it with the other projects for a future repo merge

**Comment by cdietrich** [comment]
with the repo merge done this is obsolete
