### ISSUE TITLE
Cleanup poms

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-maven#2]

**Comment by cdietrich** [comment]
the pom should be cleaned and proper work with jenkins snapshots

**Comment by spoenemann** [comment]
What exactly should be done here?

**Comment by cdietrich** [comment]
well the poms especially on my test cleanup branch should be checked, reviewed and freeed from unneccessary stuff + maybe should have a different handling regarding upstream, sonatype oss usage etc.

**Comment by spoenemann** [comment]
Done with 0c2b8ef
