### ISSUE TITLE
Xtext Maven Plugin has no way to set compiler arguments

### ISSUE THREAD

**Issue by rosczja** [eclipse/xtext-maven#23]
There is no way to set compiler arguments which are then passed down to the compiler that compiles the stubs.

I would need to switch off annotation processing and to set the "-parameters" flag.

**Comment by szarnekow** [comment]
See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=481920

It would be good to point to the prefs file in the project .settings (at least optionally)

**Comment by rosczja** [comment]
Maybe. Or do this: https://github.com/eclipse/xtext-extras/issues/372

**Comment by szarnekow** [comment]
This would require to maintain the settings twice. If you have them already in Eclipse, it would be good to work with these.
And the other way round would eventually be interesting, too. If you configured the settings in maven, you want them to be applied in Eclipse, too, after you import the project with m2e.

**Comment by rosczja** [comment]
I would expect my project to work without ever having to use Eclipse just to set compiler arguments and often Eclipse project settings are not under version control.

In Maven you set compiler arguments in the maven-compiler-plugin, like  so:
```

<configuration>
  <compilerArgs>
            <arg>-verbose</arg>
            <arg>-Xlint:all,-options,-path</arg>
   </compilerArgs>
</configuration>
```

So again nothing I could reuse in my xtext-maven plugin, because there are no properties for this, like the source encoding property.

If I am not missing something I do not see any other option as to replicate such configuration for the xtext-maven-plugin.

**Comment by szarnekow** [comment]
I'm not arguing against the proposed solution. I'm just saying, that other use cases may be solved by pointing to the eclipse preferences file. Similar to what is done for the output configuration already.

**Comment by rosczja** [comment]
Ok.

So this would be a two-way approach:

1. Enhance CompilerConfiguration and xtext-maven-plugin to pass compiler arguments
2. Check if Eclipse project settings can be used if they are present

**Comment by cdietrich** [comment]
@rosczja @rosczja can this be closed now?

**Comment by rosczja** [comment]
@cdietrich Yes this can be closed now
