### ISSUE TITLE
org.eclipse.xtext.maven.OutputConfiguration lacks several org.eclipse.xtext.generator.OutputConfiguration options

### ISSUE THREAD

**Issue by OLibutzki** [eclipse/xtext-maven#30]
There are several options which are provided by _org.eclipse.xtext.generator.OutputConfiguration_, but not included in _org.eclipse.xtext.maven.OutputConfiguration_:

* setDerivedProperty
* keepLocalHistory

I would like to configure my Eclipse project based on the Maven config by using the corresponding m2e connector which is not possible as I cannot specify the mentioned options.

**Comment by cdietrich** [comment]
i have the feeling they are missing by intention. since maven does not support these properties afaik

**Comment by kthoms** [comment]
Right, Maven does not have concepts of 'derived' or 'local history'. This is specific to the Eclipse file system.

**Comment by cdietrich** [comment]
but i am not sure if we should offer these anyway (with documentation) and have a look what our m2e stuff does with it

**Comment by OLibutzki** [comment]
An alternative solution (which I prefer) is to use the OutputConfiguration of the DSL runtime module as default. In the maven config you can override these defaults and do not have to provide the whole configuration. 

Except the output path most of (or all?) the configuration options need to be fixed by the DSL anyway.

Examples:
It does not make sense to configure a output configuration as overrideExistingResources in the maven pom, if the DSL declares it as "generate once".

Currently the DSL output configuration properties are overriden once you add the output configuration in your pom.xml. Even worse: The m2e connector sets "Mark generated files as derived" to true which is a bad default in conjunction with overrideExistingResources=false.

**Comment by cdietrich** [comment]
i would prefer a lightweight solution here first. it would fix the problem and not be a breaking change

**Comment by OLibutzki** [comment]
Can you clarify how a "lightweight solution" looks like? ;-)

**Comment by cdietrich** [comment]
Simply add the 2 missing properties and ignore it from maven

**Comment by cdietrich** [comment]
Fixed in 2.15
