### ISSUE TITLE
org.eclipse.xtext.maven.OutputConfiguration lacks setName method

### ISSUE THREAD

**Issue by OLibutzki** [eclipse/xtext-maven#62]
org.eclipse.xtext.maven.OutputConfiguration seems to lack a setName(String) method. Therefore it's not possible to override output configurations except the default one (IFileSystemAccess.DEFAULT_OUTPUT).

**Comment by cdietrich** [comment]
i wonder why there is no setName

**Comment by cdietrich** [comment]
hmmm maven proposes me name although there is no setter.
@OLibutzki did you actually try it out?

**Comment by OLibutzki** [comment]
Hmm, no, just stumbled upon this... maybe the field is set via reflection? But then I wonder why the other fields have setters.

**Comment by cdietrich** [comment]
seems to work without setter too, but we will add it for consistency

**Comment by cdietrich** [comment]
Fixed in 2.17
