### ISSUE TITLE
Allow concurrent code generation accross modules in parallelized multi-module builds, by using forking

### ISSUE THREAD

**Issue by ciis0** [eclipse/xtext-maven#96]
Hello there. :)

As already discussed in #36, real parallelization for xtext generation won't work as EMF is inherently non-threadsafe.

In our project we have a huge build (170+ modules) that already builds in parallel (thanks to #37). This has improved our build times already (currently roughly 1h parallel in contrast to 2h sequentially).
Especially in the early part we have many modules that are independent from each other but due to using xtext for code generation still block due to the Lock. This leaves room for improvement.

We are now thinking about making the xtext plugin work in parallel by forking new JVMs which then run the actual EMF processes (like surefire does for Unit tests) to further improve our build times (at the expense of increased resource usage).

This issue is to inform you about our intentions. :)
I plan to open a PR when we have some code that does at least something, as soon as we actually start implementing this.

Thank you.

**Comment by szarnekow** [comment]
Thank you for the heads-up. Why do you think that multiple JVMs will help? Building Xtext will eventually update the Xtext index in the host vm. Apart from that, resource sets could be used in parallel for the independent modules.
Just wondering, how multiple JVMs fit into the picture.

**Comment by ciis0** [comment]
I am refering to this statement: https://github.com/eclipse/xtext-maven/issues/36#issuecomment-395565788
> [...] EMF is non thread-safe without any chance to do something about this. [...]

The simplest way around this is to launch each EMF generation in it's own JVM so (missing) thread-safety is not a problem.

**Comment by ciis0** [comment]
> Apart from that, resource sets could be used in parallel for the independent modules.

What are you referring to here?
I am unfortunately not (yet?) familiar with Xtext, EMF and the likes. :)

**Comment by cdietrich** [comment]
will close this for now. feel free to reopen in github.com/eclipse/xtext
